#default project info followed by actual injected pom-specified values.
project:
  name: enjoei-perfil
  version: 0.1
  description: API de perfil para o enjoei2
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

spring:
  application:
      name: perfil
  main:
    banner-mode: "off"
    
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-50-17-194-186.compute-1.amazonaws.com:5432/d96s008caq17v8
    username: zmrlqlswfjnquy
    password: 110fe140eeb97738cf3ba50a2f28c89f7d0dfc3457aa75d498541ef2c4c7239b
    driverClassName: org.postgresql.Driver

         
basepackages: br.com.enjoei2.perfil

# SERVER
server: 
    port: 7864
    
#End points de gerenciamento em porta separada.
management:
  port: 7863
  security:
    enabled: false

#spring-boot-starter-mail properties
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: enjoei2.assistencia@gmail.com
      password: perfil-enjoei
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
          ssl:
            enable: false
      test-connection: true